#!/bin/sh

game_name=Anonymine
conf_dir=/etc/anonymine
executable=/usr/local/games/anonymine

echo 'Add new user for playing Anonymine remotely'
echo 'Enter user name (no spaces, quotes, slashes or colons are allowed):'
read username
homedir=$conf_dir/$username
sudo adduser --home $homedir --shell $executable --ingroup games $username
