#!/bin/bash

# Automatically set up an Anonymine server on Windows.
# This requires Administrator privileges.

# Self-explanatory
crap ()
{
    echo 'Crap: something went wrong' >&2
    while [ $# -gt 0 ]; do
        echo $1
        shift
    done
    exit 1
}
test -d /cygdrive || crap "This is not Cygwin"

crap "This is experimental stuff"
# To uninstall SSH to reinstall it with this script:
# cygrunsrv --stop sshd
# cygrunsrv --remove sshd
# nano /etc/passwd
# net user sshd /delete
# net user cyg_server /delete
# /setup.exe -R `cygpath --windows /` -x openssh

# We probably don't want to mess something up.
if [ -n "`which sshd`" ]; then
    echo "This script assumes that the SSH daemon has not been" >&2
    echo "installed.  Running this script could potentially mess" >&2
    echo "up your configuration.  If you wish to continue," >&2
    echo "modify this script to do so.  But don't touch unless" >&2
    echo "you know what you're doing." >&2
    exit 1
fi

echo 'WARNING: This script is sensitive to race-conditions.'
echo '  /etc/passwd will be appended to'
echo '  /etc/shells will be appended to'
echo '  /etc/sshd_config is assumed to be untouched'
echo '  /etc/sshd_config will be appended to'
echo '  ssh-host-config will be run'
read -p 'Continue (yes/*): ' continue_execution
if [ "$continue_execution" != "yes" ]; then
    echo 'Execution stopped on demand from user'
    exit 1
fi

# Configuration
echo 'The username MUST be a valid unix username and a valid Windows username'
echo 'Allowed: Alphanumerics + hyphens, periods and underscores in the middle'
read -p 'Enter username for Anonymine account: ' anonymine_username
read -p 'Enter (weak) password: ' anonymine_password

# Install the SSH daemon
/setup.exe --wait -q -R `cygpath --windows /` -P openssh cygrunsrv \
    || crap "setup.exe is not /setup.exe from within Cygwin"
ssh-host-config -c ntsec -N cygwin-sshd -y || crap "ssh-host-config failed"

# Configure sshd
echo "AllowUsers $anonymine_username" >> /etc/sshd_config

# Add the user and Anonymine as a shell
echo `which anonymine` >> /etc/shells
net user $anonymine_username "$anonymine_password" \
    /activate yes /comment 'Anonymine over SSH account' \
    || crap "Failed to add user $anonymine_username"
line="`mkpasswd -l -u $anonymine_username | cut -f 6 -d :`"
echo "$line:`which anonymine`" >> /etc/passwd

# Launch SSH daemon
net start cygwin-sshd
