#!/usr/bin/python
{
    'init-field': {
        'procs':        3,      # N logical processors on the system
                                # minus M reserved for other processes.
        'filename':     '/tmp/mines.{0}',
        'maxtime':      1.2,    # The longest reasonable solving time
                                # of a possible field.
    },
}
