#!/bin/sh

# TODO: This was created to simplify Windows support, it's no longer needed.

# Usage: ./dist srcdir builddir pkgname
srcdir=$1
builddir=$2
pkgname=$3
pkgdir=$builddir$pkgname

NAME="anonymine"
# Add .txt for Windows.
textfiles="BUGS ChangeLog FAQ INSTALL NEWS README LICENSE desktop/FILES \
    desktop/README RELEASE-NOTES INSTALL.Haiku"
# Already CRLF + shell scripts
noconv="configure check.sh desktop/desktop.sh desktop/${NAME}-*.png \
    desktop/${NAME}*.xcf mkenginecfg mkdist"
# LF to CRLF conversion for the zip
files="${NAME}.py ${NAME}_engine.py ${NAME}_fields.py ${NAME}_solver.py \
    configure.py Makefile.static install-cfg enginecfg.default cursescfg \
    test.py testcfg desktop/Info.plist.py desktop/icon.icns.py"
subdirs="desktop"


mkdir $pkgdir
for subdir in $subdirs; do
    mkdir "$pkgdir/$subdir"
done

    for f in $textfiles $noconv $files; do
        cp "$srcdir$f" "$pkgdir/$f"
    done
    cd $builddir
    tar -cf "$pkgname.tar" "$pkgname"
    gzip -9 -k "$pkgname.tar" || echo no gzip
    xz -9e -k "$pkgname.tar" || echo no xz
    rm "$pkgdir.tar"

rm -r "$pkgdir"
