#!/bin/sh

# vmsetup
# Set up a dedicated virtual machine (Debian 8)

# Do the installation magic when vmsetup, update-anonymine,
# calibrate-anonymine and addplayer are installed on the system.

oldpwd=`pwd`

echo 'You will be asked to change this password'
echo 'When you type your password, you will not see anything'
passwd

sudo apt-get install make
sudo apt-get install git

cd
mkdir dl-area

update-anonymine
# update-anonymine is also responsible for calibration.

sudo add-shell /usr/local/games/anonymine

echo 'No user for playing Anonymine has been added yet'
addplayer

cd "$oldpwd"

echo 'Installation is now complete'
echo 'Ctrl+D to logout'
