#!/bin/sh

# vmsetup
# Set up a dedicated virtual machine (Debian 8)

# Do the installation magic when vmsetup, update-anonymine,
# calibrate-anonymine and addplayer are installed on the system.

oldpwd=`pwd`

echo 'You will be asked to change this password'
echo 'When you type your password, you will not see anything'
passwd

echo
echo 'Installing make and git... You will be asked for your *new* password'
sudo apt-get install make
sudo apt-get install git

# git clone in ~/dl-area
cd
mkdir dl-area

update-anonymine
# update-anonymine is also responsible for calibration.

sudo add-shell /usr/local/games/anonymine

echo 'No user for playing Anonymine has been added yet'
addplayer

sudo cp /dev/null /etc/motd

__EOF__

cd "$oldpwd"

echo 'Installation is now complete'
echo 'Ctrl+D to logout'
